import json
from collections import defaultdict


MODEL_STR = "cogvideox"
RESOLUTION = "720p"
INPUT_JSON_FILE = f'sp_named_metrics/reusable_data_list_{MODEL_STR}_{RESOLUTION}_sp4.json'
OUTPUT_PYTHON_FILE = f'bucket_config_for_{MODEL_STR}_{RESOLUTION}_sp4.py'

RESOLUTION_MAP = {
    (352, 656): "480px",
    (1280, 720): "960px",
    (1072, 1936): "1080px",
    # (min_dim, max_dim): "group_name",
}

def get_bucket_key(h, w):
    key = tuple(sorted((h, w)))
    
    if key in RESOLUTION_MAP:
        return RESOLUTION_MAP[key]
    else:
        print(f"Warning: undefined H/W combination {h}x{w}. Falling back to the group name '{h}x{w}'.")
        return f"{h}x{w}"

def process_data(data):
    buckets = defaultdict(dict)

    for item in data:
        if len(item) != 5:
            print(f"Warning: skipping a malformed entry: {item}")
            continue
        
        bs, frames, _, h, w = item
        
        bucket_key = get_bucket_key(h, w)
        
        if frames not in buckets[bucket_key] or bs > buckets[bucket_key][frames][1]:
            buckets[bucket_key][frames] = (1.0, bs)
            
    return dict(buckets)

def write_output_file(processed_data):
    with open(OUTPUT_PYTHON_FILE, 'w', encoding='utf-8') as f:
        f.write("# This file is auto-generated by a script.\n\n")
        f.write("bucket_config = {\n")
        
        for bucket_key in sorted(processed_data.keys()):
            bucket_content = processed_data[bucket_key]
            f.write(f'    "{bucket_key}": {{\n')
            
            sorted_frames = sorted(bucket_content.items())
            
            for frames, value in sorted_frames:
                f.write(f'        {frames}: {value},\n')
                
            f.write('    },\n')
            
        f.write("}\n")

def main():
    try:
        with open(INPUT_JSON_FILE, 'r', encoding='utf-8') as f:
            input_data = json.load(f)
        
        if not isinstance(input_data, list):
            print(f"Error: the contents of '{INPUT_JSON_FILE}' must be a JSON array (list).")
            return
            
        processed_data = process_data(input_data)
        write_output_file(processed_data)
        
        print(f"\nDone. Result written to '{OUTPUT_PYTHON_FILE}'.")
        
    except FileNotFoundError:
        print(f"Error: input file '{INPUT_JSON_FILE}' not found.")
    except json.JSONDecodeError:
        print(f"Error: input file '{INPUT_JSON_FILE}' is not valid JSON.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()