import json
from collections import defaultdict


MODEL_STR = "cogvideox"
RESOLUTION = "720p"
# --- 配置 ---
INPUT_JSON_FILE = f'sp_named_metrics/reusable_data_list_{MODEL_STR}_{RESOLUTION}_sp4.json'
OUTPUT_PYTHON_FILE = f'bucket_config_for_{MODEL_STR}_{RESOLUTION}_sp4.py'

# --- 您定义的H/W分辨率到分组名称的映射规则 ---
# 为了处理例如 1280x720 和 720x1280 是同一种情况，
# 我们将 (min(h, w), max(h, w))作为键。
RESOLUTION_MAP = {
    (352, 656): "480px",
    (1280, 720): "960px",
    (1072, 1936): "1080px",
    # 您可以在这里添加更多规则...
    # (min_dim, max_dim): "group_name",
}

def get_bucket_key(h, w):
    """
    根据h和w的组合，从RESOLUTION_MAP中查找对应的分组名。
    """
    # 创建一个标准化的键，忽略h和w的顺序
    key = tuple(sorted((h, w)))
    
    # 从映射中查找分组名
    if key in RESOLUTION_MAP:
        return RESOLUTION_MAP[key]
    else:
        # 如果规则未定义，打印警告并使用 "hxw" 作为默认分组名
        print(f"警告: 发现未定义的 H/W 组合: {h}x{w}。将使用默认分组名 '{h}x{w}'。")
        return f"{h}x{w}"

def process_data(data):
    """
    处理原始数据，按h/w组合分组，并找出每个frames对应的最大bs。
    """
    buckets = defaultdict(dict)

    for item in data:
        if len(item) != 5:
            print(f"警告: 跳过格式不正确的条目: {item}")
            continue
        
        bs, frames, _, h, w = item
        
        # 根据新的规则获取分组名
        bucket_key = get_bucket_key(h, w)
        
        # 检查当前帧数是否已经记录，如果未记录或发现了更大的bs，则更新
        if frames not in buckets[bucket_key] or bs > buckets[bucket_key][frames][1]:
            buckets[bucket_key][frames] = (1.0, bs)
            
    return dict(buckets)

def write_output_file(processed_data):
    """
    将处理后的数据写入到Python文件中。
    """
    with open(OUTPUT_PYTHON_FILE, 'w', encoding='utf-8') as f:
        f.write("# This file is auto-generated by a script.\n\n")
        f.write("bucket_config = {\n")
        
        for bucket_key in sorted(processed_data.keys()):
            bucket_content = processed_data[bucket_key]
            f.write(f'    "{bucket_key}": {{\n')
            
            sorted_frames = sorted(bucket_content.items())
            
            for frames, value in sorted_frames:
                f.write(f'        {frames}: {value},\n')
                
            f.write('    },\n')
            
        f.write("}\n")

def main():
    """
    主函数：读取、处理并写入文件。
    """
    try:
        with open(INPUT_JSON_FILE, 'r', encoding='utf-8') as f:
            input_data = json.load(f)
        
        if not isinstance(input_data, list):
            print(f"错误: '{INPUT_JSON_FILE}' 的内容必须是一个JSON数组(列表)!")
            return
            
        processed_data = process_data(input_data)
        write_output_file(processed_data)
        
        print(f"\n处理完成! 结果已保存到 '{OUTPUT_PYTHON_FILE}' 文件中。")
        
    except FileNotFoundError:
        print(f"错误: 输入文件 '{INPUT_JSON_FILE}' 未找到。")
    except json.JSONDecodeError:
        print(f"错误: 输入文件 '{INPUT_JSON_FILE}' 不是一个有效的JSON文件。")
    except Exception as e:
        print(f"发生未知错误: {e}")

if __name__ == "__main__":
    main()